# Generated by Django 5.0.6 on 2024-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_created_at_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
